version: "3"

services:
  db:
    container_name: db
    image: mariadb:11.7.2@sha256:fcc7fcd7114adb5d41f14d116b8aac45f94280d2babfbbb71b4782922ee6d8d4
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    networks:
      - wordpress-net

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    build: .
    volumes:
      - wordpress_data:/var/www/html
      - ..:/var/www/html/wp-content/themes/no-theme
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEFAULT_THEME', 'no-theme');
    networks:
      - wordpress-net

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.28.0-alpine@sha256:aed99734248e851764f1f2146835ecad42b5f994081fa6631cc5d79240891ec9
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - wordpress-net

networks:
  wordpress-net:
    driver: bridge

volumes:
  db_data:
  wordpress_data:
