name: Create Theme Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "1: Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: "2: Pack theme files"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: "no-theme.zip"
          path: .
